version: '3'

networks:
  cote:
    driver: overlay

services:
  api:
    image: vojtechpospichal/underholding
    networks:
      - cote
    command: node microservices/api.js
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      - PG=true
      - COTE_DISCOVERY_REDIS_HOST=redis
      - VIRTUAL_HOST=local-api.underholding.cz, ws://local-api.underholding.cz
      - SERVICE_PORTS=5000
      - BALANCE=source
    depends_on:
      - redis

  ocr:
    networks:
      - cote
    image: vojtechpospichal/underholding
    command: node microservices/ocrService.js
    restart: on-failure
    environment:
      - PG=true
      - COTE_DISCOVERY_REDIS_HOST=redis
      - VIRTUAL_HOST=local-local-db.underholding.cz, ws://local-db.underholding.cz
      - SERVICE_PORTS=5001
      - BALANCE=source
    depends_on:
      - redis

  db:
    networks:
      - cote
    image: vojtechpospichal/underholding
    command: node microservices/dbService.js
    restart: on-failure
    environment:
      - PG=true
      - COTE_DISCOVERY_REDIS_HOST=redis
      - VIRTUAL_HOST=local-local-db.underholding.cz, ws://local-db.underholding.cz
      - SERVICE_PORTS=5002
      - BALANCE=source
    depends_on:
      - redis

  redis:
    image: redis
    networks:
      - cote
    ports:
      - 6379:6379

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - cote
    ports:
      - 3306:3306
    volumes:
      - ./sql_dump/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=25791998
      - MYSQL_DATABASE=rezervator